apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  volumes:
    - name: volume-share
	  emptyDir: {}
	  
  containers:
    - name: volume-container-datacenter-1
      image: fedora:latest
	  command: ["sleep"]
	  args: ["infinity"]
	  volumeMounts:
		- name: volume-share
		  mountPath: /tmp/beta
		  
    - name: volume-container-datacenter-2
      image: fedora:latest
	  command: ["sleep"]
	  args: ["infinity"]
	  volumeMounts:
		- name: volume-share
		  mountPath: /tmp/games
